version: '3'
services:
  toolbox:
    build:
      context: .
      dockerfile: Dockerfile
    image: toolbox_dev
    container_name: toolbox_dev
    environment:
      - JSON_API_HOST=https://jsonplaceholder.typicode.com